# Generated by Django 2.2.12 on 2021-04-09 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_email',
            field=models.EmailField(max_length=254, verbose_name='Email do comentário'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_name',
            field=models.CharField(max_length=250, verbose_name='Nome do comentário'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='Post do comentário'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que comentou'),
        ),
    ]
