# Generated by Django 2.2.12 on 2021-04-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210406_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name_cat',
            field=models.CharField(max_length=50, verbose_name='Categoria'),
        ),
    ]
